name: ajfimoveis.com.br deployment

on: 
  push:
    branches: [master]

jobs:
  checkout-code:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

  deploy-production:
    runs-on: ubuntu-latest
    needs: checkout-code
    environment:
      name: production
      url: ${{ vars.URL }}
    steps:
      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc"
          SOURCE: "/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
          SCRIPT_AFTER: |
            cd domains/ajfimoveis.com.br/public_html
            # Instala as dependências PHP
            composer2 install --no-dev --no-interaction --no-progress --prefer-dist
            # Instala as dependências JS
            rm -rf node_modules/
            npm install --y
            npm run build
            # Atualiza o cache da aplicação
            php artisan optimize
            # Atualiza as dependências
            composer2 update
            # Realiza as migrações
            php artisan migrate --force
            # Finalzia as atualizações
            php artisan up 