name: ajfimoveis.com.br deployment

on: 
  push:
    branches: [master]

jobs:
  deploy-production:

    runs-on: ubuntu-latest 
    
    environment:
      name: production
      url: ${{ vars.URL }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
      
        with: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc"
          SOURCE: "/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
          SCRIPT_AFTER: |
            cd domains/ajfimoveis.com.br/public_html
            
            # Atualiza as dependências
            if composer2 update; then
              echo "Composer update succeeded."
            else
              echo "Composer update failed."
              exit 1  # Encerra o script se falhar
            fi

            # Executa as migrações
            if php artisan migrate; then
              echo "Migrations ran successfully."
            else
              echo "Migrations failed."
              exit 1  # Encerra o script se falhar
            fi